spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate